// Interface automatically generated by schemas-to-ts

import { Profile } from '@/types/profile';
import { Profile_Plain } from '@/types/profile';

export interface AboutBlock {
  profile?: { data: Profile };
}
export interface AboutBlock_Plain {
  profile?: Profile_Plain;
}

export interface AboutBlock_NoRelations {
  profile?: number;
}
