// Interface automatically generated by schemas-to-ts

import { Industry } from '@/types/industry';
import { Project } from '@/types/project';
import { Industry_Plain } from '@/types/industry';
import { Project_Plain } from '@/types/project';

export interface Block {
  industry?: { data: Industry };
  projects: { data: Project[] };
}
export interface Block_Plain {
  industry?: Industry_Plain;
  projects: Project_Plain[];
}

export interface Block_NoRelations {
  industry?: number;
  projects: number[];
}
