// Interface automatically generated by schemas-to-ts

import { Contact } from '@/types/contact';
import { Contact_Plain } from '@/types/contact';

export interface Cta {
  Title?: string;
  Description?: string;
  contacts: { data: Contact[] };
}
export interface Cta_Plain {
  Title?: string;
  Description?: string;
  contacts: Contact_Plain[];
}

export interface Cta_NoRelations {
  Title?: string;
  Description?: string;
  contacts: number[];
}
