// Interface automatically generated by schemas-to-ts

export interface FeaturedComponent {
  Title?: string;
}
export interface FeaturedComponent_Plain {
  Title?: string;
}

export interface FeaturedComponent_NoRelations {
  Title?: string;
}

