// Interface automatically generated by schemas-to-ts

export interface Greeting {
  Title?: string;
  Subheading?: string;
}
export interface Greeting_Plain {
  Title?: string;
  Subheading?: string;
}

export interface Greeting_NoRelations {
  Title?: string;
  Subheading?: string;
}

