// Interface automatically generated by schemas-to-ts

import { Media } from '@/types/Media';
import { AdminPanelRelationPropertyModification } from '@/types/AdminPanelRelationPropertyModification';

export interface Profile {
  id: number;
  attributes: {
    createdAt: Date;
    updatedAt: Date;
    publishedAt?: Date;
    Title?: string;
    Introduction: string;
    Background: string;
    Link?: any;
    Image: { data: Media };
    Slug?: string;
  };
}
export interface Profile_Plain {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  Title?: string;
  Introduction: string;
  Background: string;
  Link?: any;
  Image: Media;
  Slug?: string;
}

export interface Profile_NoRelations {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  Title?: string;
  Introduction: string;
  Background: string;
  Link?: any;
  Image: number;
  Slug?: string;
}

export interface Profile_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  Title?: string;
  Introduction: string;
  Background: string;
  Link?: any;
  Image: AdminPanelRelationPropertyModification<Media>;
  Slug?: string;
}
